test: try a simple smoke test

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -6,23 +6,31 @@ on:
       - main
   pull_request: null
 
+concurrency:
+  group: tests
+
 jobs:
   tests:
     name: tests
     runs-on: "ubuntu-latest"
     steps:
-      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
-
-      - uses: mamba-org/setup-micromamba@f8b8a1e23a26f60a44c853292711bacfd3eac822 # v1
+      - uses: .
         with:
-          environment-name: relock-env
-          create-args: >-
-            python
-            click
-            ruamel.yaml
-            conda
-            conda-lock
-            ruff
-          condarc: |
-            channels:
-                - conda-forge
+          environment-file: test-env.yml
+          lock-file: conda-lock.yml
+          ignored-packages: ''
+          relock-all-packages: false
+          github-token: ${{ secrets.GITHUB_TOKEN }}
+          automerge: false
+
+      - name:
+        shell: bash
+        run: |
+          if [ -f conda-lock.yml ]; then
+            :  # do nothing
+          else
+            echo "conda-lock.yml not found"
+            exit 1
+          fi
+          grep numpy conda-lock.yml
+          grep python conda-lock.yml
